export enum ResponseMessage {
  // Common Success
  SUCCESS = "Success",
  FETCH_SUCCESS = "Data fetched successfully",
  UPDATE_SUCCESS = "Data updated successfully",
  CREATE_SUCCESS = "Data created successfully",
  DELETE_SUCCESS = "Data deleted successfully",

  // Auth & Profile
  LOGIN_SUCCESS = "Login successful",
  LOGOUT_SUCCESS = "Logged out successfully",
  SIGNUP_INITIATED = "OTP sent to email. Please verify to complete signup.",
  SIGNUP_SUCCESS = "User registered successfully",
  PASSWORD_UPDATE_SUCCESS = "Password changed successfully",
  PASSWORD_RESET_LINK_SENT = "Password reset link sent to your email",
  PASSWORD_RESET_OTP_SENT = "Password reset OTP sent to email",
  PASSWORD_RESET_SUCCESS = "Password reset successfully",
  OTP_VERIFIED = "OTP verified successfully",
  PROFILE_UPDATE_SUCCESS = "Profile updated successfully",
  PROFILE_IMAGE_UPDATE_SUCCESS = "Profile image updated successfully",
  USER_UPDATED = "User updated successfully",
  USER_BLOCK_TOGGLED = "User block status toggled successfully",
  USER_BLOCKED = "User blocked successfully",
  USER_UNBLOCKED = "User unblocked successfully",

  // Account / PDA
  DEPOSIT_SUCCESS = "Deposit successful",
  PAYMENT_VERIFIED = "Payment verified successfully",
  BILL_PAID_SUCCESS = "Bill paid successfully",

  // Yard / Operations
  BLOCK_CREATED = "Block created successfully",
  BLOCK_UPDATED = "Block updated successfully",
  CONTAINER_CREATED = "Container created successfully",
  CONTAINER_UPDATED = "Container updated successfully",
  CONTAINER_BLACKLISTED = "Container blacklisted successfully",
  CONTAINER_UNBLACKLISTED = "Container unblacklisted successfully",
  GATE_OPERATION_SUCCESS = "Gate operation recorded successfully",
  REQUEST_CREATED = "Container request created successfully",
  REQUEST_UPDATED = "Container request updated successfully",
  EQUIPMENT_CREATED = "Equipment created successfully",
  EQUIPMENT_UPDATED = "Equipment updated successfully",
  EQUIPMENT_DELETED = "Equipment deleted successfully",
  VEHICLE_CREATED = "Vehicle created successfully",
  VEHICLE_UPDATED = "Vehicle updated successfully",
  VEHICLE_DELETED = "Vehicle deleted successfully",
  SHIPPING_LINE_CREATED = "Shipping line created successfully",
  SHIPPING_LINE_UPDATED = "Shipping line updated successfully",

  // Billing
  BILL_CREATED = "Bill created successfully",
  ACTIVITY_CREATED = "Activity created successfully",
  ACTIVITY_UPDATED = "Activity updated successfully",
  CHARGE_CREATED = "Charge created successfully",
  CHARGE_UPDATED = "Charge updated successfully",
  CARGO_CATEGORY_CREATED = "Cargo category created successfully",
  CARGO_CATEGORY_UPDATED = "Cargo category updated successfully",

  // Support
  SUPPORT_QUERY_SUCCESS = "Query processed successfully",
  NOTIFICATION_READ = "Notification marked as read",
  NOTIFICATION_ALL_READ = "All notifications marked as read",
  NOTIFICATION_DELETED = "Notification deleted successfully",

  // Notification Titles
  PAYMENT_SUCCESSFUL_TITLE = "Payment Successful",
  PAYMENT_SUCCESSFUL_PDA_TITLE = "Payment Successful (PDA)",
  LOW_PDA_BALANCE_ALERT_TITLE = "Low PDA Balance Alert",
  REQUEST_STATUS_UPDATED_TITLE = "Request Status Updated",
  EQUIPMENT_STATUS_UPDATED_TITLE = "Equipment Status Updated",
  NEW_GATE_MOVEMENT_TITLE = "New Gate Movement",
  CONTAINER_STATUS_CHANGED_TITLE = "Container Status Changed",
  NEW_CONTAINER_ADDED_TITLE = "New Container Added",
  CONTAINER_BLACKLISTED_TITLE = "Container Blacklisted",
  PENDING_APPROVALS_TITLE = "Pending Approvals",
  DAMAGED_CONTAINER_TITLE = "Damaged Container",
  EQUIPMENT_DOWN_TITLE = "Equipment Down",
  EQUIPMENT_MAINTENANCE_TITLE = "Equipment Maintenance",

  // Errors (Generic)
  UNAUTHORIZED = "Unauthorized",
  USER_NOT_FOUND = "User not found",
  PASSWORD_MISMATCH = "Passwords do not match",
  NO_FILE_UPLOADED = "No image file provided",
  FORBIDDEN = "Access denied",
  NOT_FOUND = "Resource not found",
  CONTAINER_NOT_FOUND = "Container not found",
  CONTAINER_REQUEST_NOT_FOUND = "Container request not found",
  FORBIDDEN_COMPLETE_ONLY = "Customers can only mark requests as completed.",
  FORBIDDEN_OWN_ONLY = "You can only update your own requests.",
  AI_CONFIG_ERROR = "AI Service Configuration Error",
  INTERNAL_SERVER_ERROR = "Internal Server Error",

  // Auth Errors
  INVALID_CREDENTIALS = "Invalid credentials",
  USER_ALREADY_EXISTS = "User already exists",
  GOOGLE_AUTH_FAILED = "Failed to authenticate with Google",
  UNAUTHORIZED_ROLE = "Access denied: Unauthorized role for this portal",
  USER_ACCOUNT_BLOCKED = "Your account has been blocked. Please contact admin.",
  INVALID_REFRESH_TOKEN = "Invalid refresh token",
  PASSWORDS_DO_NOT_MATCH = "Passwords do not match",
  OAUTH_USER_PASSWORD_ERROR = "Cannot update password for OAuth users",
  INCORRECT_CURRENT_PASSWORD = "Current password is incorrect",

  // OTP Errors
  INVALID_OTP = "Invalid OTP",
  OTP_EXPIRED = "OTP has expired",

  // Billing / PDA Errors
  BILL_NOT_FOUND = "Bill not found",
  BILL_OWNERSHIP_ERROR = "Unauthorized: This bill does not belong to you",
  BILL_ALREADY_PAID = "Bill is already paid",
  PDA_INSUFFICIENT_BALANCE = "Insufficient balance in PDA",
  BILL_STATUS_UPDATE_FAILED = "Failed to update bill status",
  BILL_ID_REQUIRED = "Bill ID is required",
  RAZORPAY_ORDER_FAILED = "Razorpay Order Creation Failed",
  INVALID_PAYMENT_SIGNATURE = "Invalid payment signature",
  PDA_NOT_FOUND = "PDA not found for user",
  INSUFFICIENT_FUNDS = "Insufficient PDA balance",

  // Operation Errors
  BLOCK_NOT_FOUND = "Block not found",
  BLOCK_FULL = "Block is at full capacity",
  CONTAINER_OUTSIDE_TERMINAL = "Container must be inside terminal for this operation",
  SHIPPING_LINE_NOT_FOUND = "Shipping Line not found",
  VEHICLE_NOT_FOUND = "Vehicle not found",
  EQUIPMENT_NOT_FOUND = "Equipment not found",
  CARGO_CATEGORY_NOT_FOUND = "Cargo Category not found",
  BLOCK_NAME_REQUIRED = "Block name is required",
  INVALID_CAPACITY = "Capacity must be greater than 0",
  ACTIVITY_ALREADY_EXISTS = "Activity with this code already exists",
  INVALID_NAME_LENGTH = "Name must be between 3 and 50 characters",
  INVALID_PHONE_FORMAT = "Invalid phone number format",
  INVALID_PASSWORD_FORMAT = "Password must be at least 8 characters long and include uppercase, lowercase, number, and special character",

  // New Tokens & General Errors
  TOKEN_MISSING = "Refresh token missing",
  SOCKET_NOT_INITIALIZED = "Socket.io not initialized!",
  GOOGLE_ID_TOKEN_FAILED = "Failed to retrieve ID token from Google",
  INVALID_GOOGLE_PAYLOAD = "Invalid Google token payload",
  ENTITY_NOT_FOUND_UPDATE = "Entity not found for update",
  TRANSACTION_NOT_FOUND = "Transaction not found",
  CONFIG_KEY_MISSING = "Configuration key is missing",
  CONFIG_KEY_NOT_NUMBER = "Configuration key must be a number",

  // PDA / Payments (Additional)
  INVALID_AMOUNT = "Invalid amount provided",
  PDA_ORDER_FAILED = "Razorpay PDA Order Creation Failed",

  // Operation Errors (Additional)
  VEHICLE_ALREADY_IN_YARD = "Vehicle is already in the yard",
  CONTAINER_ALREADY_IN_TERMINAL = "Container is already inside terminal or in an invalid state",
  PENDING_BILLS_ERROR = "Cannot gate-out due to pending/overdue bills",
  CONTAINER_BLACKLISTED_ERROR = "Container is blacklisted",
  CHARGE_ALREADY_EXISTS_ERROR = "Charge rate already exists for this configuration",
  DUPLICATE_DESTUFF_REQUEST = "An active destuffing request already exists for this container",
  NOT_READY_FOR_DISPATCH_ERROR = "Container is allocated to a customer and must be \"Ready for Dispatch\" status before gate-out.",

  // Notifications
  NEW_CONTAINER_REQUEST_TITLE = "New Container Request",
  NEW_CONTAINER_REQUEST_MESSAGE = "A new request has been submitted by a customer",
  PAYMENT_RECEIVED_MESSAGE = "Your payment has been received successfully",
  PDA_PAYMENT_PROCESSED_MESSAGE = "Your payment has been processed successfully using your PDA balance",
  LOW_PDA_BALANCE_MESSAGE = "Your PDA balance is low. Please recharge to avoid payment delays.",
  GATE_OPERATION_NOT_FOUND = "Gate operation not found",
  NO_TOKEN = "No token provided",
  INVALID_TOKEN = "Invalid or expired token",
  INSUFFICIENT_PERMISSIONS = "Access denied: Insufficient permissions",
  OVERDUE_BILLS_ERROR = "Access Denied: You have overdue bills. Please settle them to access this feature.",

  // History & Audit Actions
  ACTION_GATE_IN = "Gate In",
  ACTION_GATE_OUT = "Gate Out",
  ACTION_CREATED = "Created",
  ACTION_BLACKLISTED = "Blacklisted",
  ACTION_UNBLACKLISTED = "Unblacklisted",
  ACTION_PROCESSED = "Processed",
  ACTION_UPDATED = "Updated",
  DETAILS_GATE_IN = "Processed Gate In operation",
  DETAILS_GATE_OUT = "Processed Gate Out operation",
  DETAILS_INITIALIZED = "Resource initialized successfully",
  DETAILS_BLACKLISTED = "Container has been blacklisted",
  DETAILS_UNBLACKLISTED = "Container has been unblacklisted",
  DETAILS_NO_CHANGES = "No changes specified",

  // Audit Log Actions
  AUDIT_GATE_IN = "CONTAINER_GATE_IN",
  AUDIT_GATE_OUT = "CONTAINER_GATE_OUT",
  AUDIT_BLACKLISTED = "CONTAINER_BLACKLISTED",
  AUDIT_UNBLACKLISTED = "CONTAINER_UNBLACKLISTED",
  AUDIT_PROFILE_UPDATED = "PROFILE_UPDATED",
  AUDIT_PASSWORD_UPDATED = "PASSWORD_UPDATED",
  AUDIT_USER_LOGIN = "USER_LOGIN",
  AUDIT_USER_LOGIN_GOOGLE = "USER_LOGIN_GOOGLE",
  AUDIT_USER_CREATED = "USER_CREATED",
  AUDIT_USER_UPDATED = "USER_UPDATED",
  AUDIT_CONTAINER_CREATED = "CONTAINER_CREATED",
  AUDIT_CONTAINER_UPDATED = "CONTAINER_UPDATED",
  AUDIT_BLOCK_CREATED = "BLOCK_CREATED",
  AUDIT_BLOCK_UPDATED = "BLOCK_UPDATED",
  AUDIT_SHIPPING_LINE_CREATED = "SHIPPING_LINE_CREATED",
  AUDIT_SHIPPING_LINE_UPDATED = "SHIPPING_LINE_UPDATED",
  AUDIT_EQUIPMENT_CREATED = "EQUIPMENT_CREATED",
  AUDIT_BILL_PAID = "BILL_PAID",
  AUDIT_REQUEST_CREATED = "REQUEST_CREATED",
  AUDIT_REQUEST_UPDATED = "REQUEST_UPDATED",
  AUDIT_SIGNUP = "SIGNUP",

  // Specific Action Labels
  ACTION_STUFFING_DISPATCH = "Stuffing dispatch",
  ACTION_DESTUFFING_DISPATCH = "Destuffing dispatch",
  ACTION_RAZORPAY_DEPOSIT = "Razorpay Deposit",
  ACTION_STATUS_CHANGED = "Status Changed",
  ACTION_LOCATION_UPDATED = "Location Updated",
  ACTION_SHIFT_OPERATION = "Shift Operation",
  ACTION_WEIGHT_UPDATED = "Weight Updated",
  ACTION_SEAL_NUMBER_UPDATED = "Seal Number Updated",
  ACTION_DAMAGE_STATUS_UPDATED = "Damage Status Updated",

  // Yard Actions (Internal/Event-driven)
  YARD_ACTION_CREATE = "CREATE",
  YARD_ACTION_UPDATE = "UPDATE",
  YARD_ACTION_DELETE = "DELETE",

  // Server / Infrastructure
  NOT_ALLOWED_BY_CORS = "Not allowed by CORS",
  SERVER_HEALTHY = "Server is healthy",
  ONLY_IMAGES_ALLOWED = "Only images are allowed",

  // Rate Limiting
  TOO_MANY_REQUESTS = "Too many requests from this IP, please try again after 15 minutes",
  TOO_MANY_LOGIN_ATTEMPTS = "Too many login attempts from this IP, please try again after an hour",
 
  // Resource Types for Audit Logs
  RESOURCE_USER = "User",
  RESOURCE_CONTAINER = "Container",
  RESOURCE_BLOCK = "Block",
  RESOURCE_REQUEST = "Request",
  RESOURCE_BILL = "Bill",
  RESOURCE_PROFILE = "Profile",
  RESOURCE_AUTH = "Auth",
  RESOURCE_SHIPPING_LINE = "ShippingLine",
  RESOURCE_ACTIVITY = "Activity",
  RESOURCE_CHARGE = "Charge",
  RESOURCE_EQUIPMENT = "Equipment",
  RESOURCE_VEHICLE = "Vehicle",
}
