export enum DomainEvents {
    AUDIT_LOG_CREATED = "AUDIT_LOG_CREATED",
    EQUIPMENT_HISTORY_CREATED = "EQUIPMENT_HISTORY_CREATED",
    CONTAINER_HISTORY_CREATED = "CONTAINER_HISTORY_CREATED",
    CHARGE_HISTORY_CREATED = "CHARGE_HISTORY_CREATED",
    GATE_OPERATION_CREATED = "GATE_OPERATION_CREATED",
    CONTAINER_UPDATED = "CONTAINER_UPDATED",
    CONTAINER_CREATED = "CONTAINER_CREATED",
    CONTAINER_BLACKLISTED = "CONTAINER_BLACKLISTED",
    YARD_BLOCK_CREATED = "YARD_BLOCK_CREATED",
    YARD_BLOCK_UPDATED = "YARD_BLOCK_UPDATED"
}

export interface IEventBus {
    emit(event: DomainEvents, ...args: unknown[]): boolean;
    on(event: DomainEvents, listener: (...args: any[]) => void | Promise<void>): this;

}
