import { IBlockRepository } from "../../domain/repositories/IBlockRepository";
import { Block } from "../../domain/entities/Block";
import { IAuditLogRepository } from "../../domain/repositories/IAuditLogRepository";
import { AuditLog } from "../../domain/entities/AuditLog";
import { UserContext } from "./AdminCreateUser";

interface CreateBlockData {
    name: string;
    capacity: number;
}

export class CreateBlock {
    constructor(
        private blockRepository: IBlockRepository,
        private auditLogRepository: IAuditLogRepository
    ) { }

    async execute(data: CreateBlockData, userContext: UserContext): Promise<void> {
        if (!data.name || data.name.trim().length === 0) {
            throw new Error("Block name is required");
        }

        if (!data.capacity || data.capacity <= 0) {
            throw new Error("Capacity must be greater than 0");
        }

        const newBlock = new Block(
            "", // ID will be generated by repository/database
            data.name.trim(),
            data.capacity,
            0 // New block starts with 0 occupied slots
        );

        const savedBlock = await this.blockRepository.save(newBlock);

        // Log audit event
        await this.auditLogRepository.save(new AuditLog(
            null,
            userContext.userId,
            userContext.userRole,
            userContext.userName,
            "BLOCK_CREATED",
            "Block",
            savedBlock.id,
            JSON.stringify({ name: data.name, capacity: data.capacity }),
            userContext.ipAddress
        ));
    }
}
