import { IYardBlockRepository } from "../../domain/repositories/IYardBlockRepository";
import { YardBlock } from "../../domain/entities/YardBlock";

interface CreateYardBlockData {
    name: string;
    capacity: number;
}

export class CreateYardBlock {
    constructor(private yardBlockRepository: IYardBlockRepository) { }

    async execute(data: CreateYardBlockData): Promise<void> {
        if (!data.name || data.name.trim().length === 0) {
            throw new Error("Block name is required");
        }

        if (!data.capacity || data.capacity <= 0) {
            throw new Error("Capacity must be greater than 0");
        }

        const newBlock = new YardBlock(
            "", // ID will be generated by repository/database
            data.name.trim(),
            data.capacity,
            0 // New block starts with 0 occupied slots
        );

        await this.yardBlockRepository.save(newBlock);
    }
}
