import { OAuth2Client, TokenPayload } from "google-auth-library";
import { IUserRepository } from "../../domain/repositories/IUserRepository";
import { ITokenService } from "../services/ITokenService";
import { User, UserRole } from "../../domain/entities/User";

export class GoogleLogin {
  private client: OAuth2Client;

  constructor(
    private userRepository: IUserRepository,
    private tokenService: ITokenService,
    private googleClientId: string,
  ) {
    if (!googleClientId) {
      throw new Error("Google client ID is required for GoogleLogin use case");
    }
    this.client = new OAuth2Client(googleClientId);
  }

  async execute(idToken: string): Promise<{
    accessToken: string;
    refreshToken: string;
    user: { id: string; email: string; role: UserRole; name?: string };
  }> {
    const ticket = await this.client.verifyIdToken({
      idToken,
      audience: this.googleClientId,
    });

    const payload: TokenPayload | undefined = ticket.getPayload();
    if (!payload || !payload.email) {
      throw new Error("Invalid Google token");
    }

    const { email, sub: googleId, name } = payload;

    if (!googleId) {
      throw new Error("Google ID(sub) missing from payload");
    }

    let user = await this.userRepository.findByGoogleId(googleId);

    if (!user) {
      //Check if user exists with the same email
      user = await this.userRepository.findByEmail(email);

      if (user) {
        // Link account if it matches email (or throw error/update)
        const updatedUser = new User(
          user.id,
          user.email,
          user.role,
          user.password,
          (user.name || name) as string | undefined,
          googleId,
        );

        await this.userRepository.save(updatedUser);
        user = updatedUser;
      } else {
        //Create new customer
        user = new User(
          "", //ID will be generated by DB
          email,
          "customer",
          undefined, //No password for Google users
          name,
          googleId,
        );

        await this.userRepository.save(user);
        //Re-fetch to get the ID if it was created
        user = await this.userRepository.findByGoogleId(googleId);
      }
    }

    if (!user) {
      throw new Error("Failed to authenticate with Google");
    }

    //Access token
    const accessToken = this.tokenService.generate(
      {
        id: user.id,
        emaila: user.email,
        role: user.role,
      },
      process.env.JWT_ACCESS_SECRET || "access_fallback",
      "15m",
    );

    // Refresh Token
    const refreshToken = this.tokenService.generate(
      { id: user.id },
      process.env.JWT_REFRESH_SECRET || "refresh_fallback",
      "7d",
    );

    return {
      accessToken,
      refreshToken,
      user: {
        id: user.id,
        email: user.email,
        role: user.role,
        name: user.name,
      },
    };
  }
}
